Repository ThunderShadows/SocialSync, pull requests merged in 2025-01, with the labels that each got.

#3 fix: removed topbar
  index.html
Labels: SWOC, Beginner

#5 Solves #4 Updated README.md
  README.md
Labels: SWOC

#13 Hover button
  css/style.css
  index.html
Labels: enhancement, SWOC

#23 adding images in about section
  about.html
Labels: enhancement, SWOC

#26 Hover Effect on Topbar Social Media Icons
  about.html
  appointment.html
  contact.html
  css/style.css
  feature.html
  service.html
  team.html
  testimonial.html
Labels: enhancement, SWOC

#32 Update the styles in the css/style.css file to improve scroll bar
  css/style.css
Labels: enhancement, SWOC

#43 change-image-in-home-section
  index.html
Labels: enhancement, SWOC

#45 Default Cursor hided
  about.html
  appointment.html
  contact.html
  css/bootstrap.min.css
  feature.html
  index.html
  lib/wow/customcursor.css
  lib/wow/customcursor.js
  service.html
  team.html
  testimonial.html
Labels: enhancement, SWOC

#48 Darkmode button added
  about.html
  appointment.html
  contact.html
  dark_mode_24dp_EFEFEF_FILL1_wght400_GRAD0_opsz24.svg
  feature.html
  index.html
  light_mode_24dp_EFEFEF_FILL1_wght400_GRAD0_opsz24.svg
  service.html
  team.html
  testimonial.html
Labels: enhancement, SWOC

#52 🚀 Fixed Overlapping Issue Between Chatbot and Scroll Button 🎯
  css/style.css
Labels: enhancement, SWOC
